# -*- coding: utf-8 -*-
"""gptCOCevent.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mgWX2ISHDCeIqCaQEYwArO93W1JbSjYg
"""



!pip install openai

import urllib.request
from PIL import Image
import cv2
from google.colab.patches import cv2_imshow

import os 
import openai 

openai.api_key = 'here add your API secret key'
openai.Model.list()

image_result = openai.Image.create(
    prompt = 'scotch cat sitting in the table eating date',
    n = 1,
    size = '512x512',
)
image_result ['data'][0]['url']
img_url = image_result['data'][0]['url']
urllib.request.urlretrieve(img_url, 'img.png')

img = cv2.imread("img.png")

cv2_imshow(img)